# Generated by Django 5.0.2 on 2024-03-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0002_news_likes_post_numberview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='categories',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='author',
            name='profile_picture',
            field=models.ImageField(upload_to='Media/profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='main_image',
            field=models.ImageField(upload_to='Media/main_images_news/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Media/thumbnails_news/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image',
            field=models.ImageField(upload_to='Media/main_images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Media/thumbnails/'),
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('email',)},
        ),
    ]
