# Generated by Django 5.0.2 on 2024-04-02 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='birth_date',
        ),
    ]
