# Generated by Django 5.0.2 on 2024-04-03 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0007_categorynews_commentnews'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryNews',
        ),
        migrations.RemoveField(
            model_name='news',
            name='Category',
        ),
        migrations.AddField(
            model_name='news',
            name='Category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='mag.category'),
        ),
    ]
