# Generated by Django 5.0.2 on 2024-04-03 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0008_delete_categorynews_remove_news_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mag.category'),
        ),
    ]
