# Generated by Django 5.0.2 on 2024-04-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0011_remove_author_profile_picture_remove_post_main_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='news',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='news',
            name='numberView',
            field=models.IntegerField(null=True),
        ),
    ]
