# Generated by Django 5.0.2 on 2024-04-14 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0013_rename_user_likenews_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.ForeignKey(default='kimi team', on_delete=django.db.models.deletion.CASCADE, to='mag.author'),
        ),
    ]
