# Generated by Django 5.0.2 on 2024-04-14 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0014_alter_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mag.author'),
        ),
    ]
