# Generated by Django 5.0.2 on 2024-04-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0017_alter_author_password_alter_author_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainimage',
            name='image',
            field=models.ImageField(upload_to='main_images/'),
        ),
        migrations.AlterField(
            model_name='mainimagenews',
            name='image',
            field=models.ImageField(upload_to='main_images_news/'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='image',
            field=models.ImageField(upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='thumbnailnews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_news/'),
        ),
    ]
