# Generated by Django 5.0.2 on 2024-04-22 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0018_alter_mainimage_image_alter_mainimagenews_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likenews',
            old_name='post',
            new_name='news',
        ),
    ]
