# Generated by Django 5.0.2 on 2024-04-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0019_rename_post_likenews_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.BigIntegerField(default='0'),
        ),
        migrations.RemoveField(
            model_name='news',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_news', to='mag.utilisateur'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, related_name='liked_posts', to='mag.utilisateur'),
        ),
    ]
